title = "Nehil Jain"
baseURL = "https://clever-banach-29cd5c.netlify.com/"
languageCode = "en-us"
tags = ["data engineering", "machine learning", "analytics"]
config = "config.toml"
theme = "osprey"
googleAnalytics = "UA-163382820-1"
canonifyURLS = true
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomy]
    tag = "tags"

[permalinks]
    blog = "/:year/:month/:day/:slug/"


[params]
    author = "Nehil Jain"
    tagline = "data, analytics & infrastructure"
    description = "🙏 I am Data Engineer who currently works at SnapTravel. I love solving problem for other comapnies who are struggling setting up reporting, infrastructure, data trust and/or reliability."
    headline = "Nehil Jain"
    logoBig = "/images/profile.jpg"
    logoSmall = "/images/profile.jpg"
    favicon = "favicon.ico"
    opengraphImage = ""
    twitter = "nehiljain"
    linkedin = "nehiljain"
    github = "nehiljain"
    email = "jain.nehil@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = true
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 2

[[menu.main]]
    name = "Lists"
    url = "/lists"
    weight = 3
