title = "Nehil Jain"
baseURL = "https://clever-banach-29cd5c.netlify.com/"
languageCode = "en-us"
tags = ["data engineering", "machine learning", "analytics"]
config = "config.toml"
theme = "osprey"
googleAnalytics = "UA-163382820-1"
canonifyURLS = true
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomy]
    tag = "tags"

[permalinks]
    blog = "/:year/:month/:day/:slug/"


[params]
    author = "Nehil Jain"
    tagline = "data, analytics & infrastructure"
    description = "🙏 I am Data Engineer who currently works at SnapTravel. I love solving problem for other comapnies who are struggling setting up reporting, infrastructure, data trust and/or reliability."
    headline = "Nehil Jain"
    logoBig = "/images/profile.jpg"
    logoSmall = "/images/profile.jpg"
    favicon = "favicon.ico"
    opengraphImage = ""
    twitter = "nehiljain"
    linkedin = "nehiljain"
    github = "nehiljain"
    email = "jain.nehil@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 2


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/nehiljain"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://ca.linkedin.com/in/nehiljain"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/971856/nehiljain"
    name = "stack-overflow"
    weight = 5
