baseURL = "https://clever-banach-29cd5c.netlify.com/"
languageCode = "en-us"
title = "Nehil Jain"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Nehil Jain"
    description = "🙏 I am Data Engineer who currently works at SnapTravel. I love solving problem for other comapnies who are struggling setting up reporting, infrastructure, data trust and/or reliability."
    githubUsername = "nehiljain"
    accent = "lightgrey"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["sql", "python", "R", "javascript", "swift"]
    profilePic = "images/profile.jpg"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/nehiljain"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://ca.linkedin.com/in/nehiljain"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/971856/nehiljain"
    name = "stack-overflow"
    weight = 5
